"""initial_v7_schema

Revision ID: bae11bc4bde5
Revises: 
Create Date: 2026-08-22 17:48:15.109914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bae11bc4bde5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required for the trigram GIN indexes on draft_replies (full-text-ish search).
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_org_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_clerk_org_id'), 'organizations', ['clerk_org_id'], unique=True)
    op.create_table('processed_webhook_events',
    sa.Column('svix_id', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('svix_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'MEMBER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('analyst_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_details_gin', 'audit_logs', ['details'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_audit_logs_org_id'), 'audit_logs', ['org_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_org_time', 'audit_logs', ['org_id', 'timestamp'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('REDDIT', 'LINKEDIN', 'TWITTER', name='platformenum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'ARCHIVED', name='campaignstatus'), nullable=False),
    sa.Column('poll_frequency_minutes', sa.Integer(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('platform_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('daily_draft_cap', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_active', 'campaigns', ['org_id'], unique=False, postgresql_where="status = 'ACTIVE'")
    op.create_index('idx_campaign_keywords_gin', 'campaigns', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_campaigns_platform'), 'campaigns', ['platform'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('REDDIT', 'LINKEDIN', 'TWITTER', name='platformenum'), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('intel_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'week_of', name='uq_intel_brief_org_week')
    )
    op.create_table('org_apify_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('encrypted_token', sa.Text(), nullable=False),
    sa.Column('encrypted_with_key_version', sa.Integer(), nullable=False),
    sa.Column('plan_cap_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('org_llm_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=True),
    sa.Column('custom_base_url', sa.String(length=500), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('encrypted_with_key_version', sa.Integer(), nullable=False),
    sa.Column('max_daily_llm_tokens', sa.Integer(), nullable=True),
    sa.Column('max_monthly_llm_cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('org_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_org_membership_org_user')
    )
    op.create_table('org_personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('master_context', sa.Text(), nullable=True),
    sa.Column('rulesets_dos_donts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tone_guidelines', sa.Text(), nullable=True),
    sa.Column('master_context_token_count', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_index('idx_orgpersona_rulesets_gin', 'org_personas', ['rulesets_dos_donts'], unique=False, postgresql_using='gin')
    op.create_table('org_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('reply_hook', sa.Text(), nullable=True),
    sa.Column('scout_prompt', sa.Text(), nullable=True),
    sa.Column('apify_monthly_budget_usd', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('actor_overrides', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('linkedin_stale_days', sa.Integer(), nullable=True),
    sa.Column('linkedin_stale_min_engagement', sa.Integer(), nullable=True),
    sa.Column('analyst_enabled', sa.Boolean(), nullable=False),
    sa.Column('disclosure_reddit', sa.Boolean(), nullable=False),
    sa.Column('pillar_taxonomy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id')
    )
    op.create_table('posted_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('REDDIT', 'LINKEDIN', 'TWITTER', name='platformenum'), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'platform', 'post_id', name='uq_posted_history_org_platform_post')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.Enum('REDDIT', 'LINKEDIN', 'TWITTER', name='platformenum'), nullable=True),
    sa.Column('type', sa.Enum('MASTER_CONTEXT', 'ANGLE', 'SCOUT', 'ANALYST', name='prompttype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_org_prompt_name')
    )
    op.create_table('subreddit_safety_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('subreddit', sa.String(length=100), nullable=False),
    sa.Column('max_daily_drafts', sa.Integer(), nullable=False),
    sa.Column('require_manual_review', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'subreddit', name='uq_org_subreddit_safety')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_replies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('REDDIT', 'LINKEDIN', 'TWITTER', name='platformenum'), nullable=False),
    sa.Column('post_id', sa.String(length=100), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=True),
    sa.Column('author_headline', sa.String(length=500), nullable=True),
    sa.Column('author_profile_url', sa.String(length=500), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('top_comments', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('reply_target_url', sa.String(length=500), nullable=True),
    sa.Column('reply_type', sa.Enum('NEW_COMMENT', 'REPLY_TO_COMMENT', name='replytype'), nullable=False),
    sa.Column('target_comment_id', sa.String(length=100), nullable=True),
    sa.Column('target_comment_content', sa.Text(), nullable=True),
    sa.Column('angle_name', sa.String(length=255), nullable=True),
    sa.Column('ai_draft_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'AWAITING_CONFIRM', 'POSTED', 'REJECTED', 'IGNORED', 'FAILED', 'FAILED_COST_LIMIT', name='draftstatus'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('triage_reasoning', sa.Text(), nullable=True),
    sa.Column('signal_tier', sa.String(length=50), nullable=True),
    sa.Column('reactions', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('engagement_score', sa.Integer(), nullable=False),
    sa.Column('posted_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('live_url', sa.String(length=500), nullable=True),
    sa.Column('reject_reason', sa.String(length=1000), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_template_version', sa.String(length=100), nullable=True),
    sa.Column('prompt_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_token_count', sa.Integer(), nullable=True),
    sa.Column('locked_by_user_id', sa.Integer(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['locked_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'post_id', name='uq_draft_campaign_post')
    )
    op.create_index('idx_draft_campaign_status_created', 'draft_replies', ['campaign_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_draft_status_org', 'draft_replies', ['org_id', 'status'], unique=False)
    op.create_index('idx_draftreply_ai_draft_text_fts', 'draft_replies', ['ai_draft_text'], unique=False, postgresql_using='gin', postgresql_ops={'ai_draft_text': 'gin_trgm_ops'})
    op.create_index('idx_draftreply_original_content_fts', 'draft_replies', ['original_content'], unique=False, postgresql_using='gin', postgresql_ops={'original_content': 'gin_trgm_ops'})
    op.create_index(op.f('ix_draft_replies_created_at'), 'draft_replies', ['created_at'], unique=False)
    op.create_index(op.f('ix_draft_replies_org_id'), 'draft_replies', ['org_id'], unique=False)
    op.create_index(op.f('ix_draft_replies_platform'), 'draft_replies', ['platform'], unique=False)
    op.create_index(op.f('ix_draft_replies_post_id'), 'draft_replies', ['post_id'], unique=False)
    op.create_index(op.f('ix_draft_replies_status'), 'draft_replies', ['status'], unique=False)
    op.create_table('post_classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('source_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision', sa.String(length=50), nullable=True),
    sa.Column('relevance', sa.Integer(), nullable=True),
    sa.Column('signal', sa.Integer(), nullable=True),
    sa.Column('buyer_persona', sa.String(length=255), nullable=True),
    sa.Column('watch_tier', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analyst_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quote_worthy_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('post_ref', sa.String(length=500), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analyst_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stance_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('post_ref', sa.String(length=500), nullable=False),
    sa.Column('stance', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_quote', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['analyst_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_clusters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.String(length=255), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('posts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['analyst_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagement_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.Integer(), nullable=False),
    sa.Column('hours_after', sa.Integer(), nullable=False),
    sa.Column('reactions', sa.Integer(), nullable=False),
    sa.Column('replies', sa.Integer(), nullable=False),
    sa.Column('reposts', sa.Integer(), nullable=False),
    sa.Column('got_response', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft_replies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engagement_outcomes')
    op.drop_table('topic_clusters')
    op.drop_table('stance_observations')
    op.drop_table('quote_worthy_claims')
    op.drop_table('post_classifications')
    op.drop_index(op.f('ix_draft_replies_status'), table_name='draft_replies')
    op.drop_index(op.f('ix_draft_replies_post_id'), table_name='draft_replies')
    op.drop_index(op.f('ix_draft_replies_platform'), table_name='draft_replies')
    op.drop_index(op.f('ix_draft_replies_org_id'), table_name='draft_replies')
    op.drop_index(op.f('ix_draft_replies_created_at'), table_name='draft_replies')
    op.drop_index('idx_draftreply_original_content_fts', table_name='draft_replies', postgresql_using='gin', postgresql_ops={'original_content': 'gin_trgm_ops'})
    op.drop_index('idx_draftreply_ai_draft_text_fts', table_name='draft_replies', postgresql_using='gin', postgresql_ops={'ai_draft_text': 'gin_trgm_ops'})
    op.drop_index('idx_draft_status_org', table_name='draft_replies')
    op.drop_index('idx_draft_campaign_status_created', table_name='draft_replies')
    op.drop_table('draft_replies')
    op.drop_table('target_authors')
    op.drop_table('system_logs')
    op.drop_table('subreddit_safety_profiles')
    op.drop_table('prompt_templates')
    op.drop_table('posted_history')
    op.drop_table('org_settings')
    op.drop_index('idx_orgpersona_rulesets_gin', table_name='org_personas', postgresql_using='gin')
    op.drop_table('org_personas')
    op.drop_table('org_memberships')
    op.drop_table('org_llm_configs')
    op.drop_table('org_apify_tokens')
    op.drop_table('intel_briefs')
    op.drop_table('competitors')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_platform'), table_name='campaigns')
    op.drop_index('idx_campaign_keywords_gin', table_name='campaigns', postgresql_using='gin')
    op.drop_index('idx_campaign_active', table_name='campaigns', postgresql_where="status = 'ACTIVE'")
    op.drop_table('campaigns')
    op.drop_index('ix_audit_org_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_org_id'), table_name='audit_logs')
    op.drop_index('idx_audit_details_gin', table_name='audit_logs', postgresql_using='gin')
    op.drop_table('audit_logs')
    op.drop_table('analyst_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('processed_webhook_events')
    op.drop_index(op.f('ix_organizations_clerk_org_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###

    # drop_table() does not drop the backing ENUM types (they may be shared),
    # so clean them up explicitly for a fully reversible downgrade.
    for enum_name in (
        "userrole", "platformenum", "campaignstatus",
        "prompttype", "replytype", "draftstatus",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")

    op.execute('DROP EXTENSION IF EXISTS pg_trgm')
